"""添加user和todo表的一对多映射关系

Revision ID: 4e2c20fdd830
Revises: 26ae2ea66484
Create Date: 2025-03-05 08:49:54.764878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e2c20fdd830'
down_revision = '26ae2ea66484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
